"""add missing ix_requests_tenant_id index

Revision ID: 594ca7479bd7
Revises: d9a1c2e3f4b5
Create Date: 2026-07-28 13:20:50.838160
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594ca7479bd7'
down_revision: Union[str, None] = 'd9a1c2e3f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_requests_tenant_id'), 'requests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_tenant_id'), table_name='requests')
    # ### end Alembic commands ###
